Repository SOPKATHON-iOS-TEAM3/Sopkathon-iOS, pull requests merged in 2024-05, with the labels that each got.

#2 [Setting] #1 - 프로젝트 기본 세팅을 했습니다.
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Sopkathon-iOS/Sopkathon-iOS.xcodeproj/project.pbxproj
  Sopkathon-iOS/Sopkathon-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Sopkathon-iOS/Sopkathon-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Sopkathon-iOS/Sopkathon-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sopkathon-iOS/Sopkathon-iOS/Application/AppDelegate.swift
  Sopkathon-iOS/Sopkathon-iOS/Application/Base.lproj/LaunchScreen.storyboard
  Sopkathon-iOS/Sopkathon-iOS/Application/SceneDelegate.swift
  Sopkathon-iOS/Sopkathon-iOS/Data/DTO.swift
  Sopkathon-iOS/Sopkathon-iOS/Global/Extension/UIView+.swift
  Sopkathon-iOS/Sopkathon-iOS/Global/Literals/FontLiterals.swift
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Fonts/Pretendard-Bold.otf
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Fonts/Pretendard-ExtraBold.otf
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Fonts/Pretendard-Light.otf
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Fonts/Pretendard-Medium.otf
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Fonts/Pretendard-Regular.otf
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Fonts/Pretendard-SemiBold.otf
  Sopkathon-iOS/Sopkathon-iOS/Global/Utils/className.swift
  Sopkathon-iOS/Sopkathon-iOS/Info.plist
  Sopkathon-iOS/Sopkathon-iOS/Network/Config.swift
  Sopkathon-iOS/Sopkathon-iOS/Network/MoyaLoggingPlugin.swift
  Sopkathon-iOS/Sopkathon-iOS/Presentation/ViewController.swift
Labels: 명진, Setting

#9 [Feat] #3 - 온보딩 와이어프레임 레이아웃 구현
  Sopkathon-iOS/Sopkathon-iOS.xcodeproj/project.pbxproj
  Sopkathon-iOS/Sopkathon-iOS/Application/SceneDelegate.swift
  Sopkathon-iOS/Sopkathon-iOS/Presentation/OnBoarding/ViewControllers/NicknameViewController.swift
  Sopkathon-iOS/Sopkathon-iOS/Presentation/OnBoarding/ViewControllers/NumOfFriendsViewController.swift
  Sopkathon-iOS/Sopkathon-iOS/Presentation/ViewController.swift
Labels: 민서, Feat

#8 [Feat] #6 - CustomButton을 구현 하였습니다.
  Sopkathon-iOS/Sopkathon-iOS.xcodeproj/project.pbxproj
  Sopkathon-iOS/Sopkathon-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sopkathon-iOS/Sopkathon-iOS/Global/Literals/FontLiterals.swift
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/gray08.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/zeroPink.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Presentation/CustomButton.swift
Labels: 명진, Feat

#15 [Feat] #11 - HomeViewController를 구현 하였습니다.
  Sopkathon-iOS/Sopkathon-iOS.xcodeproj/project.pbxproj
  Sopkathon-iOS/Sopkathon-iOS/Global/Literals/FontLiterals.swift
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/imgCloud.imageset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/imgCloud.imageset/cloud.svg
  Sopkathon-iOS/Sopkathon-iOS/Presentation/Home/HomeViewController.swift
Labels: 명진, Feat

#16 [Feat] #3 - 온보딩 UI 구현
  Sopkathon-iOS/Sopkathon-iOS/Application/Base.lproj/LaunchScreen.storyboard
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray01.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray02.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray03.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray04.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray05.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray06.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray07.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray08.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray09.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray10.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray11.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray12.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray13.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray14.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/Gray15.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/GrayScale/White.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/MainColor/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/MainColor/background.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/MainColor/main_pink.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/MainColor/sub_blue.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/MainColor/sub_purple.colorset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/img_onBoarding.imageset/Contents.json
  Sopkathon-iOS/Sopkathon-iOS/Global/Resource/Assets.xcassets/img_onBoarding.imageset/Group 1000002407.svg
  Sopkathon-iOS/Sopkathon-iOS/Presentation/CustomButton.swift
  Sopkathon-iOS/Sopkathon-iOS/Presentation/OnBoarding/ViewControllers/NicknameViewController.swift
  Sopkathon-iOS/Sopkathon-iOS/Presentation/OnBoarding/ViewControllers/NumOfFriendsViewController.swift
Labels: 민서, Feat
